--- 
abstract: Extract data from an HTML table
author: 
  - Diab Jerius (djerius@cpan.org)
build_requires: 
  Test::More: 0.32
distribution_type: module
generated_by: Module::Install version 0.68
license: gpl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-TableParser
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Entities: 0
  HTML::Parser: 3.26
version: 0.37.1
